version: '2'

services:
  django_srv:
    extends:
      file: docker-compose.yml
      service: django_srv
    volumes:
      - "./tests/django_srv/flesh:/srv"
      - "/srv/.venv"
      - "./stickybeak:/srv/.venv/lib/python3.7/site-packages/stickybeak"
    ports:
      - "8000:8000"

  stickybeak:
    extends:
      file: docker-compose.yml
      service: stickybeak
    volumes:
      - ".:/srv"
      - "/srv/.venv"

  flask_srv:
    extends:
        file: docker-compose.yml
        service:
          flask_srv
    volumes:
      - "./tests/flask_srv/flesh:/srv"
      - "/srv/.venv"
      - "./stickybeak:/srv/.venv/lib/python3.7/site-packages/stickybeak"

networks:
  network:
