version: '3.5'

services:
  django_srv:
    container_name: django-srv
    build:
      dockerfile: ./tests/django_srv/Dockerfile
      context: .
    command: ./bin/cont/start
    restart: always
    networks:
      - network
    volumes:
      - "./tests/django_srv/flesh:/srv"
      - "/srv/.venv"
      - "./stickybeak:/srv/.venv/lib/python3.7/site-packages/stickybeak"

  stickybeak:
    container_name: stickybeak
    build: .
    command: "tail -f /dev/null"
    restart: always
    networks:
      - network
    volumes:
      - ".:/srv"
      - "/srv/.venv"

  flask_srv:
    container_name: flask-srv
    build:
      dockerfile: ./tests/flask_srv/Dockerfile
      context: .
    command: ./bin/cont/start
    restart: always
    networks:
      - network
    volumes:
      - "./tests/flask_srv/flesh:/srv"
      - "/srv/.venv"
      - "./stickybeak:/srv/.venv/lib/python3.7/site-packages/stickybeak"

networks:
  network:
