version: '3.5'

services:
  django_srv:
    container_name: django-srv
    hostname: django-srv
    build:
      dockerfile: ./tests/django_srv/Dockerfile
      context: .
    command: ./bin/cont/start
    restart: always
    networks:
      - network
    volumes:
      - "./tests/django_srv:/srv"
      - "./stickybeak:/usr/local/lib/python3.7/site-packages/stickybeak"
    environment:
      - TEST_ENV=TEST_ENV_VALUE

  stickybeak:
    hostname: stickybeak
    container_name: stickybeak
    build: .
    user: root
    command: /usr/bin/supervisord
    restart: always
    networks:
      - network
    volumes:
      - ".:/srv"
      - ".:/tmp/pycharm_project_208/"
    environment:
      - TEST_ENV=TEST_ENV_VALUE

  flask_srv:
    container_name: flask-srv
    build:
      dockerfile: ./tests/flask_srv/Dockerfile
      context: .
    command: ./bin/cont/start
    restart: always
    networks:
      - network
    volumes:
      - "./tests/flask_srv:/srv"
      - "./stickybeak:/usr/local/lib/python3.7/site-packages/stickybeak"
    environment:
      - TEST_ENV=TEST_ENV_VALUE

networks:
  network:
